# Generated by Django 3.1 on 2021-03-03 08:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0022_auto_20210213_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wave2.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
