# Generated by Django 3.1 on 2021-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wave2', '0022_auto_20210213_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField()),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('was_mentor', models.BooleanField()),
                ('elsys', models.SmallIntegerField()),
                ('organization', models.CharField(max_length=100)),
                ('pozition', models.CharField(max_length=100)),
                ('free', models.CharField(max_length=250)),
                ('tshirt_size', models.CharField(max_length=5)),
                ('agreed', models.TextField()),
                ('xp', models.TextField()),
                ('technologies', models.ManyToManyField(blank=True, to='wave2.Technology')),
            ],
        ),
    ]
