# Generated by Django 3.1 on 2021-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave3', '0002_auto_20210227_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='elsys',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
