# Generated by Django 3.1 on 2021-03-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave3', '0004_mentor_displayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='pozition',
            new_name='position',
        ),
    ]
